### ISSUE TITLE
Minor syntax errors at end of rtest_qm.mac

### ISSUE THREAD

**Issue by robert-dodier** [QMeqGR/qm-maxima#5] opened 2024-10-20 05:27 UTC
Couple of minor syntax errors at the end of rtest_qm.mac.

(1) The `4.ket([n])` in `(ap+am)^^4.ket([n])` is parsed as `4 ket([n])` since `4.` is interpreted as 4 in base 10, whatever the value of `ibase`. Need to put a space after 4 so that it's interpreted as noncommutative multiplication.

(2) Missing semicolon at end of expected result.

Here's a patch for both of those items.

```{diff}
diff --git a/docs/rtest_qm.mac b/docs/rtest_qm.mac
index ac8a13e..0858c1b 100644
--- a/docs/rtest_qm.mac
+++ b/docs/rtest_qm.mac
@@ -598,5 +598,5 @@ sqrt(n+1)*ket([n+1]) $
 am.ket([n]);
 ket([n-1])*sqrt(n) $
 
-bra([n]).(ap+am)^^4.ket([n]);
-6*n^2+6*n+3 
+bra([n]).(ap+am)^^4 .ket([n]);
+6*n^2+6*n+3;
```

**Comment by QMeqGR** [comment] 2024-10-20 14:18
Thank you for the patch. The issue was caused by my script that automatically generates the rtest file. I pushed a fix that resolves the issue. However I do get some tests that fail while the expected output and generated output are identical. I'm still looking into that. For the format of the rtest file I'm using:

input ;
expected output $ 

Should I have the expected output terminated with ";"?

**Comment by robert-dodier** [comment] 2024-10-20 16:33
No, for test scripts it doesn't matter whether the input and expected result are terminated by semicolon or by dollar sign. I'm also looking at the failed tests; from what I see, it appears to have something to do with the implementation of `tpket`. I'll open a separate ticket if I can figure something out.

**Comment by QMeqGR** [comment] 2024-10-20 18:02
OK. I'll close this out since the push fixes the issue with the dot operator, and then I'll focus on the new ticket.

**Closed as completed by QMeqGR** 2024-10-20 18:02 UTC
